import React, { lazy, Suspense, useEffect, useState } from 'react';
import { Routes, Route, Link, NavLink, Navigate, Outlet, useLocation } from 'react-router-dom';
import { LayoutDashboard, Building2, HardHat, Wallet, Bell, Settings, User, Menu, X, LogOut, ClipboardList, Truck, CalendarDays, ArrowUpRight } from 'lucide-react';
import { useStore } from './Store.jsx';
import { Logo, Empty } from './UI.jsx';
import { sections, titleCase } from './routes.js';
const Public = lazy(()=>import('./Public.jsx'));
const Workspace = lazy(()=>import('./Workspace.jsx'));
const icons = {dashboard:LayoutDashboard,projects:Building2,bids:ClipboardList,contractors:HardHat,workers:HardHat,equipment:Truck,attendance:CalendarDays,payments:Wallet,earnings:Wallet,expenses:Wallet,notifications:Bell,profile:User,settings:Settings};
function ScrollReset(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo(0,0);document.title=`${pathname==='/'?'Build better. Together.':titleCase(pathname.split('/').filter(Boolean).at(-1))} · OBRIX`;},[pathname]);return null;}
function PublicLayout(){ const {user}=useStore(); const [open,setOpen]=useState(false); const location=useLocation(); useEffect(()=>setOpen(false),[location.pathname]); return <><a className="skip-link" href="#main">Skip to content</a><header className="public-header"><div className="container nav-row"><Logo/><button className="icon-button mobile-toggle" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'public-nav open':'public-nav'} aria-label="Main navigation"><NavLink to="/projects">Projects</NavLink><NavLink to="/equipment">Equipment</NavLink><NavLink to="/contractors">Contractors</NavLink><NavLink to="/workers">Workers</NavLink><NavLink to="/how-it-works">How it works</NavLink><Link className="btn small" to={user?`/${user.role}/dashboard`:'/login'}>{user?'Workspace':'Get started'}<ArrowUpRight size={16}/></Link></nav></div></header><main id="main"><Outlet/></main><footer><div className="container footer-grid"><div><Logo/><p>Strong foundations.<br/>Stronger connections.</p><small>Frontend demo · No real transactions</small></div><div><h4>Explore</h4><Link to="/projects">Projects</Link><Link to="/equipment">Equipment</Link><Link to="/workers">Skilled workers</Link></div><div><h4>OBRIX</h4><Link to="/about">About us</Link><Link to="/how-it-works">How it works</Link><Link to="/signup">Join the ecosystem</Link></div></div><div className="container footer-bottom">© {new Date().getFullYear()} OBRIX. Built for the people who build India.<span>DELHI · INDIA</span></div></footer></>; }
function DashboardLayout({role}){const {user,state,act}=useStore();const [open,setOpen]=useState(false);const {pathname}=useLocation();useEffect(()=>setOpen(false),[pathname]);if(!user)return <Navigate to="/login" replace/>;if(user.role!==role)return <Navigate to={`/${user.role}/dashboard`} replace/>;const unread=state.notifications.filter(n=>n.userId===user.id&&!n.read).length;return <div className={`workspace ${state.settings[user.id]?.compact?'compact':''}`}><a className="skip-link" href="#main">Skip to content</a>{open&&<button className="sidebar-scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={`sidebar ${open?'open':''}`}><Logo/><div className="workspace-label">{role} workspace</div><nav aria-label={`${role} navigation`}>{sections[role].map(page=>{const Icon=icons[page]||ClipboardList;return <NavLink key={page} to={`/${role}/${page}`}><Icon size={18}/>{titleCase(page)}{page==='notifications'&&unread>0&&<span className="count">{unread}</span>}</NavLink>;})}</nav><div className="sidebar-bottom"><Link to="/projects">Explore marketplace <ArrowUpRight size={15}/></Link><button onClick={()=>act('LOGOUT',{},'Signed out')}><LogOut size={17}/>Sign out</button><small>DEMO WORKSPACE · LOCAL DATA</small></div></aside><div className="workspace-main"><header className="topbar"><div className="actions"><button className="icon-button mobile-toggle" aria-label="Open navigation" aria-expanded={open} onClick={()=>setOpen(true)}><Menu/></button><span className="breadcrumb">Workspace <span>/</span> {titleCase(pathname.split('/')[2]||'dashboard')}</span></div><div className="actions"><Link className="demo-switch" to="/login">Switch demo role</Link><Link className="icon-button notification-button" to={`/${role}/notifications`} aria-label={`${unread} unread notifications`}><Bell size={20}/>{unread>0&&<i/>}</Link><Link className="top-user" to={`/${role}/profile`}><span className="avatar small">{user.name[0]}</span><span>{user.name}<small>{titleCase(role)}</small></span></Link></div></header><main id="main" className="dashboard-content"><Outlet/></main><div className="dashboard-footer">OBRIX / Build better. Together.<span>All payments and accounts are simulated.</span></div></div></div>;}
export default function App(){return <><ScrollReset/><Suspense fallback={<div className="loading" role="status"><span className="spinner"/>Loading your OBRIX workspace…</div>}><Routes><Route element={<PublicLayout/>}>{['','how-it-works','projects','equipment','contractors','workers','about','login','signup'].map(page=><Route key={page} path={page||'/'} element={<Public page={page||'home'}/>}/>)}<Route path="projects/:id" element={<Public page="project-detail"/>}/><Route path="equipment/:id" element={<Public page="equipment-detail"/>}/></Route>{Object.entries(sections).map(([role,pages])=><Route key={role} path={role} element={<DashboardLayout role={role}/>}><Route index element={<Navigate to="dashboard" replace/>}/>{pages.map(page=><Route key={page} path={page} element={<Workspace key={`${role}/${page}`} page={page}/>}/>)}{role!=='worker'&&<Route path="projects/:id" element={<Workspace page="project-detail"/>}/ >}{role==='company'&&<Route path="projects/new" element={<Workspace page="project-new"/>}/ >}{role==='contractor'&&<Route path="projects/:id/bid" element={<Workspace page="bid-new"/>}/ >}</Route>)}<Route path="*" element={<div className="container section"><Empty title="This page isn't on the blueprint"><Link className="btn" to="/">Back to OBRIX</Link></Empty></div>}/></Routes></Suspense></>;}
