import React, { useEffect, useId, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Building2, HardHat, MapPin, Search, X, Inbox } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { money } from './data.js';
import { useStore } from './Store.jsx';
export const Logo = () => <Link to="/" className="logo" aria-label="Obrix home"><span><Building2 size={23}/></span>OBRIX<i>®</i></Link>;
export const Badge = ({ children }) => <span className={`badge ${String(children).toLowerCase().replaceAll(' ', '-')}`}>{children}</span>;
export const Empty = ({ title = 'Nothing here yet', children }) => <div className="empty"><Inbox size={34}/><h3>{title}</h3><p>{children || 'Your activity will appear here as you use the workspace.'}</p></div>;
export const Heading = ({ eyebrow = 'YOUR CONNECTED WORKSPACE', title, description, children }) => <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description && <p>{description}</p>}</div><div className="actions">{children}</div></div>;
export const Stat = ({ label, value, detail, icon: Icon = Building2 }) => <div className="stat"><div className="stat-label">{label}<Icon size={18}/></div><strong>{value}</strong><small>{detail}</small></div>;
export function Dialog({ title, children, onClose }) {
  const ref = useRef(), id = useId();
  useEffect(() => { const prior = document.activeElement; const root = ref.current; root.focus(); const old = document.body.style.overflow; document.body.style.overflow = 'hidden';
    const key = e => { if (e.key === 'Escape') onClose(); if (e.key === 'Tab') { const items = [...root.querySelectorAll('button:not(:disabled),input,select,textarea,a[href]')]; const first = items[0], last = items[items.length - 1]; if (e.shiftKey && (document.activeElement === first || document.activeElement === root)) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } };
    root.addEventListener('keydown', key); return () => { document.body.style.overflow = old; root.removeEventListener('keydown', key); prior?.focus(); };
  }, [onClose]);
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby={id} tabIndex={-1} ref={ref}><div className="section-title"><h2 id={id}>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></div>{children}</section></div>;
}
export function Confirm({ children, title = 'Confirm action', message, onConfirm, danger = false }) {
  const [open, setOpen] = useState(false), [error, setError] = useState('');
  return <><button className={danger ? 'btn danger small' : 'btn secondary small'} onClick={() => { setError(''); setOpen(true); }}>{children}</button>{open && <Dialog title={title} onClose={() => setOpen(false)}><p>{message || 'This updates the shared demo workspace for all affected roles.'}</p>{error && <p className="error" role="alert">{error}</p>}<div className="actions mt-6"><button className="btn secondary" onClick={() => setOpen(false)}>Cancel</button><button className={`btn ${danger ? 'danger' : ''}`} onClick={() => { try { onConfirm(); setOpen(false); } catch (e) { setError(e.message); } }}>Confirm</button></div></Dialog>}</>;
}
export function ActionForm({ fields, initial = {}, onSubmit, submit = 'Save changes' }) {
  const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  return <form className="form-grid" onSubmit={async e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); setError(''); setBusy(true); try { await onSubmit(data); } catch (err) { setError(err.message); } finally { setBusy(false); } }}>
    {fields.map(f => <label className={f.wide || f.type === 'textarea' ? 'wide' : ''} key={f.name}>{f.label}<span className="field-hint">{f.hint}</span>{f.options ? <select name={f.name} defaultValue={initial[f.name] ?? f.value ?? ''} required={f.required !== false}><option value="" disabled>Select {f.label.toLowerCase()}</option>{f.options.map(o => <option key={typeof o === 'string' ? o : o.value} value={typeof o === 'string' ? o : o.value}>{typeof o === 'string' ? o : o.label}</option>)}</select> : f.type === 'textarea' ? <textarea name={f.name} rows={4} maxLength={3000} defaultValue={initial[f.name] ?? ''} required={f.required !== false}/> : <input name={f.name} type={f.type || 'text'} defaultValue={initial[f.name] ?? f.value ?? ''} min={f.min ?? (f.type === 'number' ? 1 : undefined)} max={f.max} step={f.step ?? (f.type === 'number' ? 'any' : undefined)} maxLength={200} required={f.required !== false} placeholder={f.placeholder}/> }</label>)}
    {error && <div className="error wide" role="alert">{error}</div>}<div className="wide"><button className="btn" disabled={busy} type="submit">{busy ? 'Saving…' : submit}<ArrowUpRight size={17}/></button></div>
  </form>;
}
export function DataTable({ columns, rows, empty }) {
  if (!rows.length) return <Empty title={empty}/>;
  return <div className="table-scroll" tabIndex={0} role="region" aria-label="Scrollable data table"><table><thead><tr>{columns.map(c => <th key={c.key} scope="col">{c.label}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={r.id || i}>{columns.map(c => <td key={c.key}>{c.render ? c.render(r) : r[c.key]}</td>)}</tr>)}</tbody></table></div>;
}
export function Explorer({ items, render, noun = 'results' }) {
  const [query, setQuery] = useState(''), [city, setCity] = useState(''), [status, setStatus] = useState(''), [sort, setSort] = useState('default');
  const locations = [...new Set(items.map(x => x.city).filter(Boolean))];
  const states = [...new Set(items.map(x => x.status || x.category || x.availability).filter(Boolean))];
  const filtered = items.filter(x => (!city || x.city === city) && (!status || (x.status || x.category || x.availability) === status) && `${x.name || ''} ${x.title || ''} ${x.description || ''} ${(x.skills || []).join(' ')} ${x.city || ''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === 'name' ? (a.name || a.title).localeCompare(b.name || b.title) : sort === 'low' ? (a.budget || a.rate || 0) - (b.budget || b.rate || 0) : sort === 'high' ? (b.budget || b.rate || 0) - (a.budget || a.rate || 0) : 0);
  return <><div className="filters"><label className="search"><Search size={18}/><input aria-label="Search listings" placeholder="Search by name, skill or location…" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="Filter city" value={city} onChange={e => setCity(e.target.value)}><option value="">All cities</option>{locations.map(v => <option key={v}>{v}</option>)}</select><select aria-label="Filter category or status" value={status} onChange={e => setStatus(e.target.value)}><option value="">All types / statuses</option>{states.map(v => <option key={v}>{v}</option>)}</select><select aria-label="Sort results" value={sort} onChange={e => setSort(e.target.value)}><option value="default">Recommended</option><option value="name">Name A–Z</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div><p className="result-count">{filtered.length} {noun}</p>{filtered.length ? <div className="card-grid">{filtered.map(render)}</div> : <Empty title="No matching results"><button className="text-link" onClick={() => { setQuery(''); setCity(''); setStatus(''); }}>Clear filters</button></Empty>}</>;
}
export function ProjectCard({ project: p, base = '/projects' }) {
  return <Link to={`${base}/${p.id}`} className="listing-card"><div className={`project-art art-${p.category === 'Residential' ? '1' : p.category === 'Industrial' ? '2' : '3'}`}><div className="building-lines"/><span className="art-number">OB / {p.id.replace('p','0').slice(0,5)}</span><Badge>{p.status}</Badge></div><div className="card-body"><span className="eyebrow">{p.category}</span><h3>{p.title}</h3><p className="location"><MapPin size={14}/>{p.city} <span>· {p.area}</span></p><div className="card-bottom"><div><small>Project budget</small><strong>{money(p.budget)}</strong></div><span className="circle-arrow"><ArrowUpRight size={19}/></span></div></div></Link>;
}
export function EquipmentCard({ equipment: e }) {
  return <Link to={`/equipment/${e.id}`} className="listing-card"><div className="equipment-art"><EquipmentArt/><Badge>{e.available ? 'Available' : 'Rented'}</Badge></div><div className="card-body"><span className="eyebrow">{e.category}</span><h3>{e.name}</h3><p className="location"><MapPin size={14}/>{e.city}</p><div className="card-bottom"><strong>{money(e.rate)}<small> / day</small></strong><ArrowUpRight size={20}/></div></div></Link>;
}
export function PersonCard({ person: p, children }) { const [open, setOpen] = useState(false); return <article className="panel person-card"><div className="section-title"><span className="avatar">{p.name.split(' ').slice(0,2).map(x=>x[0]).join('')}</span><Badge>{p.availability}</Badge></div><h3>{p.name}</h3><p className="location"><MapPin size={14}/>{p.city} · ★ {p.rating || 'New'}</p><div className="tags">{p.skills.map(s=><span key={s}>{s}</span>)}</div><p>{p.bio || 'Ready to build with OBRIX.'}</p><div className="actions"><button className="btn secondary small" onClick={()=>setOpen(true)}>View profile</button>{children}</div>{open && <Dialog title={p.name} onClose={()=>setOpen(false)}><p>{p.bio}</p><p>{p.city} · {p.email}</p><p>{p.phone}</p><div className="tags">{p.skills.map(s=><span key={s}>{s}</span>)}</div>{p.rate && <p>Daily rate: {money(p.rate)}</p>}<small>Mock directory profile. No real contact or verification service.</small></Dialog>}</article>; }
export function Chart({ data, title = 'Financial overview', series = [{ key: 'amount', color: '#F7C600' }] }) {
  return <section className="panel"><h2>{title}</h2><p className="muted">Recorded demo transactions · INR</p>{data.length ? <><div className="chart" role="img" aria-label={`${title}: ${data.map(d=>`${d.name} ${series.map(s=>money(d[s.key])).join(', ')}`).join('; ')}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} width={58} tickFormatter={v=>v>=1000?`${Math.round(v/1000)}k`:v}/><Tooltip formatter={v=>money(v)}/>{series.map(s=><Bar key={s.key} dataKey={s.key} fill={s.color} radius={[4,4,0,0]} maxBarSize={44}/>)}</BarChart></ResponsiveContainer></div><div className="tags">{series.map(s=><span key={s.key}><i style={{background:s.color}} className="legend-dot"/>{s.key}</span>)}</div></> : <Empty title="No transactions yet"/>}</section>;
}
export function EquipmentArt() { return <svg viewBox="0 0 400 220" aria-hidden="true"><path d="M0 188H400" stroke="#bcbcb3"/><path d="M90 137h130l25 27H75z" fill="#F7C600"/><path d="M110 137V88h52v49M121 126V99h29v27" fill="#202723" fillRule="evenodd"/><path d="m168 128 62-62 22 6 56 78-15 12-60-63-47 45" fill="#e3b600"/><path d="m287 150 17-12 31 28-3 18-46-2z" fill="#262c28"/><circle cx="103" cy="167" r="24" fill="#202723"/><circle cx="103" cy="167" r="10" fill="#92988f"/><circle cx="191" cy="167" r="29" fill="#202723"/><circle cx="191" cy="167" r="12" fill="#92988f"/></svg>; }
export function ConstructionArt() { return <svg viewBox="0 0 580 530" className="construction-svg" aria-hidden="true"><defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0H0V28" fill="none" stroke="#ffffff" strokeOpacity=".06"/></pattern><pattern id="windows" width="30" height="34" patternUnits="userSpaceOnUse"><rect x="6" y="6" width="17" height="21" fill="#9ba59b" fillOpacity=".32"/></pattern></defs><rect width="580" height="530" fill="url(#grid)"/><path d="M35 460 295 510 545 395 290 350Z" fill="#2e3730"/><path d="M80 450V200l130-35v315z" fill="#667466"/><path d="m210 165 95 55v286l-95-26z" fill="#303c32"/><path d="M87 205h118v260H87z" fill="url(#windows)"/><path d="M310 420V95l100-27v317z" fill="#899386"/><path d="m410 68 87 58v297l-87-38z" fill="#3f4d40"/><path d="M320 100h83v281h-83z" fill="url(#windows)"/><path d="M257 450V45h14v405M158 78h277M200 78l64-45 115 45M264 80v140M400 80v119" fill="none" stroke="#F7C600" strokeWidth="6"/><path d="M248 444h33M393 199h14v10h-14" stroke="#F7C600" strokeWidth="6"/><text x="35" y="40" fill="#b0b9ae" fontSize="12" letterSpacing="3">BUILDING WHAT'S NEXT / 01</text></svg>; }
export function ExportButton() { const { state } = useStore(); return <button className="btn secondary" onClick={()=>{ const url = URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})); const a=document.createElement('a'); a.href=url; a.download='obrix-workspace.json'; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }}>Export workspace JSON</button>; }
